#!/bin/bash

prefix=/home/inspur/fmc/packages
lib=/usr/lib64

rpm -ivh $prefix/zlib-1.2.3-29.el6.x86_64.rpm $prefix/libjpeg-turbo-1.2.1-3.el6_5.x86_64.rpm --force &&
rpm -ivh $prefix/gdal-1.9.2-4.el6.x86_64.rpm $prefix/gdal-libs-1.9.2-4.el6.x86_64.rpm &&
rpm -ivh $prefix/hdf5-1.8.9-1.el6.x86_64.rpm --force &&
ln -s $lib/libhdf5.so.7 $lib/libhdf5.so.8 
ln -s $lib/libhdf5_hl.so.7 $lib/libhdf5_hl.so.8
